-- https://school.programmers.co.kr/learn/courses/30/lessons/131117

SELECT P.PRODUCT_ID, P.PRODUCT_NAME,SUM(P.PRICE * O.AMOUNT) TOTAL_SALES FROM FOOD_PRODUCT P
JOIN FOOD_ORDER O ON P.PRODUCT_ID=O.PRODUCT_ID
WHERE PRODUCE_DATE LIKE "2022-05%"
GROUP BY PRODUCT_ID
ORDER BY SUM(P.PRICE * O.AMOUNT) DESC, PRODUCT_ID ASC