-- https://school.programmers.co.kr/learn/courses/30/lessons/157341
SELECT DISTINCT(C.CAR_ID) FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE H.START_DATE LIKE '2022-10%' AND C.CAR_TYPE='세단'
ORDER BY C.CAR_ID DESC