-- https://school.programmers.co.kr/learn/courses/30/lessons/133026
SELECT I.INGREDIENT_TYPE, SUM(H.TOTAL_ORDER) TOTAL_ORDER FROM FIRST_HALF H
JOIN ICECREAM_INFO I ON H.FLAVOR=I.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY SUM(H.TOTAL_ORDER)